### ISSUE TITLE
Unknown Mailgun Error

### ISSUE THREAD

**Issue by fahmiardhianto** [jorgemanrubia/mailgun_rails#55]
I have follow the usage guide by setting config.action_mailer to mailgun and using my api_key and my domain, but I get this error message that unfortunately doesn't help.
```
Mailgun::DeliveryError: Unknown Mailgun Error
	from /home/fahmi/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/mailgun-rails-0.1.1/lib/mailgun-rails.rb:51:in `deliver!'
	from /home/fahmi/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/mail-2.6.3/lib/mail/message.rb:252:in `deliver!'
	from /home/fahmi/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/actionmailer-4.2.3/lib/action_mailer/message_delivery.rb:77:in `deliver_now!'
	from /home/fahmi/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/actionmailer-4.2.3/lib/action_mailer/message_delivery.rb:95:in `deliver!'
	from (irb):3
	from /home/fahmi/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/railties-4.2.3/lib/rails/commands/console.rb:110:in `start'
	from /home/fahmi/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/railties-4.2.3/lib/rails/commands/console.rb:9:in `start'
	from /home/fahmi/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/railties-4.2.3/lib/rails/commands/commands_tasks.rb:68:in `console'
	from /home/fahmi/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/railties-4.2.3/lib/rails/commands/commands_tasks.rb:39:in `run_command!'
	from /home/fahmi/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/railties-4.2.3/lib/rails/commands.rb:17:in `<top (required)>'
	from bin/rails:4:in `require'
	from bin/rails:4:in `<main>'
```
Am I missing something?

**Comment by fahmiardhianto** [comment]
My bad, I'm still playing around in development and found out that the from domain must match my mailgun domain.
