### ISSUE TITLE
RestClient::ResourceNotFound (404 Resource Not Found)

### ISSUE THREAD

**Issue by raffe90** [jorgemanrubia/mailgun_rails#58]
I have deployed my app to Digital Ocean and while it seems to work correctly in development, in production I keep getting that message.

Any ideas as to why that might be happening? 

I should also mention, this is happening with Devise, upon confirming the account.

**Comment by bsodmike** [comment]
I can confirm the same issue here,

```
   (1.0ms)  ROLLBACK
RestClient::ResourceNotFound: 404 Resource Not Found: <!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 3.2 Final//EN">
<title>404 Not Found</title>
<h1>Not Found</h1>
<p>The requested URL was not found on the server.</p><p>If you entered the URL manually please check your spelling and try again.</p>

	from /home/deploy/.bundler/gplink_ie_staging/ruby/2.2.0/gems/rest-client-1.6.7/lib/restclient/abstract_response.rb:48:in `return!'
	from /home/deploy/.bundler/gplink_ie_staging/ruby/2.2.0/gems/rest-client-1.6.7/lib/restclient/request.rb:230:in `process_result'
	from /home/deploy/.bundler/gplink_ie_staging/ruby/2.2.0/gems/rest-client-1.6.7/lib/restclient/request.rb:178:in `block in transmit'
	from /usr/local/lib/ruby/2.2.0/net/http.rb:853:in `start'
	from /home/deploy/.bundler/gplink_ie_staging/ruby/2.2.0/gems/rest-client-1.6.7/lib/restclient/request.rb:172:in `transmit'
	from /home/deploy/.bundler/gplink_ie_staging/ruby/2.2.0/gems/rest-client-1.6.7/lib/restclient/request.rb:64:in `execute'
	from /home/deploy/.bundler/gplink_ie_staging/ruby/2.2.0/gems/rest-client-1.6.7/lib/restclient/request.rb:33:in `execute'
	from /home/deploy/.bundler/gplink_ie_staging/ruby/2.2.0/gems/rest-client-1.6.7/lib/restclient.rb:72:in `post'
	from /home/deploy/.bundler/gplink_ie_staging/ruby/2.2.0/gems/mailgun_rails-0.8.0/lib/mailgun/client.rb:14:in `send_message'
	from /home/deploy/.bundler/gplink_ie_staging/ruby/2.2.0/gems/mailgun_rails-0.8.0/lib/mailgun/deliverer.rb:19:in `deliver!'
	from /home/deploy/.bundler/gplink_ie_staging/ruby/2.2.0/gems/mail-2.6.4/lib/mail/message.rb:2149:in `do_delivery'
	from /home/deploy/.bundler/gplink_ie_staging/ruby/2.2.0/gems/mail-2.6.4/lib/mail/message.rb:237:in `block in deliver'
	from /home/deploy/.bundler/gplink_ie_staging/ruby/2.2.0/gems/actionmailer-5.0.0.beta3/lib/action_mailer/base.rb:541:in `block in deliver_mail'
```

**Comment by bsodmike** [comment]
Just tested this with a Rails 5 app, not seeing any issues here.

**Comment by johny** [comment]
I can confirm, I am also seeing this issue

**Comment by foysalit** [comment]
Seeing the same error myself. I'm running ubuntu 14.04 on digitalocean. 
rails 4.2.6 and mailgun_rails 0.8.0.

**Comment by ArielAleksandrus** [comment]
So no developpers came here to say anything? Could you solve your problem?

**Comment by foysalit** [comment]
@ArielAleksandrus no response from the maintainers so far. I'm quite new to rails and have no idea even where to start looking at. otherwise, I would be happy to submit a PR with a fix.

**Comment by atomkirk** [comment]
I'm seeing this with Rails 5 on Heroku. The problem is that RestClient offers NOTHING to help debug this. It simply prints `RestClient::ResourceNotFound (404 Resource Not Found):` to the logs and then…nothing

**Comment by atomkirk** [comment]
PR to log specific error response from mailgun: https://github.com/jorgemanrubia/mailgun_rails/pull/67

**Comment by garybunofsky** [comment]
Also experiencing this issue with Rails 4.2.3 on Heroku.

**Comment by bsodmike** [comment]
@garybunofsky could you confirm that your Mailgun config is setup correctly?

**Comment by garybunofsky** [comment]
As far as I know it is. I have `mailgun_api_key`, `mailgun_domain` and `mailgun_sender` set in my `secrets.yml`. My production.rb has the following to override actionmailer: 

`config.action_mailer.delivery_method = :mailgun
  config.action_mailer.mailgun_settings = {
    api_key: Rails.application.secrets.mailgun_api_key,
    domain: Rails.application.secrets.mailgun_domain
  }`

Is any of that improper? Could having `gem 'mailgun-ruby', '1.1.0', require: 'mailgun'` and `gem 'mailgun_rails'` in my  Gemfile be the issue?

**Comment by bsodmike** [comment]
Hmm, my stack is deployed via Chef (AWS OpsWorks) and I template those setting via env vars, here's an example: - this keeps the keys outside the code-base (and git tracking), which is very important!

``` ruby
# production.rb

  config.action_mailer.delivery_method = :mailgun
  config.action_mailer.mailgun_settings = {
    api_key: ENV['MAILGUN_API_KEY'],
    domain: ENV['MAILGUN_DOMAIN']
  }
```

As an aside, here's my `secrets.yml`

``` ruby
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
```

My `Gemfile.lock` shows `mailgun_rails (0.8.0)` and the `Gemfile` just has `gem 'mailgun_rails'`.

I'd suggest as a starting point, drop into a console in production and test to see what `Rails.application.secrets.mailgun_api_key` and `mailgun_domain` give you.

Then, try forcing v0.8.0, and see if that does anything differently.

So far, mailgun is working find here, latest Rails 5 app too.

**Comment by garybunofsky** [comment]
Thanks @bsodmike. I did what you suggested and used environment variables instead of `Rails.application.secrets`. I'm no longer getting the `RestClient::ResourceNotFound (404 Resource Not Found):` error. I appreciate your help.

For anyone else experiencing this issue and using using devise, make sure your `devise.rb` has the proper sender. e.g.
`config.mailer_sender = ENV["MAILGUN_SENDER"]`

**Comment by bsodmike** [comment]
Fantastic, thanks! :metal:

**Comment by naterexw** [comment]
I had to use the following ENV variables to get mine to work:
```
  config.action_mailer.mailgun_settings = {
    api_key: ENV["MAILGUN_API_KEY"],
    domain: ENV["MAILGUN_DOMAIN"],
    user_name: ENV["MAILGUN_SMTP_LOGIN"],
    password: ENV["MAILGUN_SMTP_PASSWORD"]
  }
```

**Comment by darrenterhune** [comment]
@naterexw errr I don't see `user_name` or `password` here https://github.com/jorgemanrubia/mailgun_rails/blob/master/lib/mailgun_rails/client.rb#L8-L12 so those are not doing much 😝

**Comment by Faisal-nfl** [comment]
> Thanks @bsodmike. I did what you suggested and used environment variables instead of `Rails.application.secrets`. I'm no longer getting the `RestClient::ResourceNotFound (404 Resource Not Found):` error. I appreciate your help.
> 
> For anyone else experiencing this issue and using using devise, make sure your `devise.rb` has the proper sender. e.g.
> `config.mailer_sender = ENV["MAILGUN_SENDER"]`

whats meant by MAILGUN_SENDER here?
like mailgun or domain?

**Comment by bsodmike** [comment]
@Faisal-nfl it'll be the default reply mail address such as "noreply@mydomain.com"
